name: Super-Linter (Global)

on:
  workflow_call: {}
  push:
    branches:
      - main
      - "**"
  pull_request:
    branches:
      - main

jobs:
  super-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          IGNORE_GITIGNORED_FILES: true
          LINTER_RULES_PATH: .github/linters
          VALIDATE_PYTHON_BLACK: true
          FIX_PYTHON_BLACK: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_DOCKERFILE_HADOLINT: true

      - name: Commit Linter Fixes
        if: always()
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          if ! git diff --quiet; then
            git add .
            git commit -m "chore: auto-fix lint errors"
            git push
          fi

