name: Super-Linter (Global)

on:
  workflow_call:
    inputs:
      languages:
        required: false
        type: string

jobs:
  super-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          IGNORE_GITIGNORED_FILES: true
          LINTER_RULES_PATH: .github/linters
          VALIDATE_PYTHON_BLACK: true
          FIX_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_YAML: true
          VALIDATE_MARKDOWN: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_DOCKERFILE_HADOLINT: true
